development:
  adapter: postgresql
  database: new_madonnas
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: new_madonnas
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: new_madonnas
  pool: 5
  timeout: 5000